### ISSUE TITLE
BC-250 16GB memory, split by default as 4/12

### ISSUE THREAD

**Issue by minjuns** [mothenjoyer69/bc250-documentation#1]
Hello,

The BC-250 recently purchased have 16GB memory, which is 4G/12G splitted by default. Its bios came with was 4.00. What I tried to do is to update firmware from the Gitlab link of the main page. I was able to see the GFX configuration menu and changed its VRAM limit sequentially from 512 MB to 8GB, but it has no changes at all when I check it through a simple HTOP command on linux, showing about 3.9GB available main memory. Probably different batch of BC-250, but I have no idea. Do you have any idea that I can adjust VRAM size to run more CPU intensive applications on BC-250? Thank you!

**Comment by mothenjoyer69** [comment]
As far as I am aware, the 4/12 models are identical hardware wise, they just came with P4.00G firmware stock which enables a 4/12 split. As long as you've followed ALL information provided you should have a customized split, could you try doing a firmware settings reset?

**Comment by mothenjoyer69** [comment]
glad to hear it :) 

i'll add a note for people coming from non-p3.00 boards :)

@minjuns follow the above steps :)

**Comment by Smig0l** [comment]
Also mine is a 4/12 model. It should have the p5.00 bios.
So if I understand correctly I should flash ( so downgrade) the modded bios provided by Segfault.
Does the VCC pin operates as 3.3 or 1.8V?
Only modding the bios allow us to allocate a custom VRAM size? Or was allowed before p3.00?
