### ISSUE TITLE
SuperIO chip

### ISSUE THREAD

**Issue by yeyus** [mothenjoyer69/bc250-documentation#3]
Hey, I've been setting up my BC-250 with fedora 41 and I found this low hanging fruit for support of the superio chip sensors.

The board reports an unknown Super I/O chip with ID `0xd441` , this seems to match other AMD boards that have a Nuvoton NCT6686D. In order for `lm-sensors` to recognize this chip the following settings must be applied.

`# modprobe nct6683 force=true`

If you want to persist these changes create the following files:

File: `/etc/modules-load.d/99-sensors.conf`
```text
nct6683
```

File: `/etc/modprobe.d/sensors.conf`
```text
options nct6683 force=true
```

The issue like everything with this board seems to be a very custom implementation, in this case a custom customer id that the nct6683 does not recognize but forcing it will work just fine.

Once enabled you should expect to see the following sensor data:

```
nct6686-isa-0a20
Adapter: ISA adapter
VIN0:             800.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN1:               1.01 V  (min =  +0.00 V, max =  +0.00 V)
VIN2:             992.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN6:               1.39 V  (min =  +0.00 V, max =  +0.00 V)
VIN7:             912.00 mV (min =  +0.00 V, max =  +0.00 V)
VIN16:            896.00 mV (min =  +0.00 V, max =  +0.00 V)
fan1:                0 RPM  (min =    0 RPM)
fan2:             2877 RPM  (min =    0 RPM)
fan3:                0 RPM  (min =    0 RPM)
fan4:                0 RPM  (min =    0 RPM)
fan5:                0 RPM  (min =    0 RPM)
AMD TSI Addr 98h:  +58.0°C  (low  =  +0.0°C)
                            (high =  +0.0°C, hyst =  +0.0°C)
                            (crit =  +0.0°C)  sensor = AMD AMDSI
Thermistor 14:     +45.5°C  (low  =  +0.0°C)
                            (high =  +0.0°C, hyst =  +0.0°C)
                            (crit =  +0.0°C)  sensor = thermistor
Thermistor 15:     +45.0°C  (low  =  +0.0°C)
                            (high =  +0.0°C, hyst =  +0.0°C)
                            (crit =  +0.0°C)  sensor = thermistor
intrusion0:       OK
beep_enable:      disabled
```

**Comment by mothenjoyer69** [comment]
Added info to readme

**Comment by mothenjoyer69** [comment]
Apparently I forgot to add this to the README. Its there now, thanks for the info :)
